### ISSUE TITLE
Error: Command failed: docker_buildx/scripts/dockerhub_login.sh

### ISSUE THREAD

**Issue by cjyar** [ilteoood/docker_buildx#18]
This is a great little utility, but I'm having trouble getting it to work. You can see the [repo](https://github.com/cjyar/openldap-docker/tree/b87fbf273c9a892ee3f1ae2b38798fbdadeb1bb5) and [build results](https://github.com/cjyar/openldap-docker/runs/1502504324?check_suite_focus=true), or read on. Here's the config I used:

```yaml
      - uses: ilteoood/docker_buildx@1.0.5
        with:
          tag: ${{ matrix.tags }}
          imageName: cjyar/openldap
          buildArg: ALPINE_VERSION=${{ matrix.alpine }},OPENLDAP_VERSION=${{ matrix.openldap }}
          publish: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch' }}
          dockerHubUser: cjyar
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
```

It said: `Error: Command failed: docker_buildx/scripts/dockerhub_login.sh cjyar ***`
